### ISSUE TITLE
Support of Python 3.10.x

### ISSUE THREAD

**Issue by FanwangM** [theochem/roberto#10]
Thanks for the nice tool for package development. 
It is noticed that the `roberto` does not support Python 3.10. Can you fix this so that we have support 3.1x for other packages? A sample error can be seen from https://github.com/theochem/procrustes/runs/5683942042?check_suite_focus=true.

 Thank you. @tovrstra

**Comment by FarnazH** [comment]
@FanwangMeng changing `3.10` to a string, i.e., `'3.10'`, seems to fix the problem; see https://github.com/FanwangMeng/procrustes/commit/1120fe0399b0541e78e30c46f29b38c9c9a3a382 (there was a failure with 3.8, but 3.10 passed). Thanks, @tczorro for figuring out this.

**Comment by FanwangM** [comment]
Thanks for helping with it. @FarnazH @tovrstra 

The failure of `Python 3.8` is caused by the new versions of `pylint` and `flake8`. The problem is resolved by specifying the package version.

**Comment by FanwangM** [comment]
So, I am going to close this issue. Thanks again for helping.
